namespace PaintApplication
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.rect = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.circle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.line = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.hello = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.canvas = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.operation = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.undo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.count = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // rect
            // 
            this.rect.AllowAnimations = true;
            this.rect.AllowMouseEffects = true;
            this.rect.AllowToggling = false;
            this.rect.AnimationSpeed = 200;
            this.rect.AutoGenerateColors = false;
            this.rect.AutoRoundBorders = false;
            this.rect.AutoSizeLeftIcon = true;
            this.rect.AutoSizeRightIcon = true;
            this.rect.BackColor = System.Drawing.Color.Transparent;
            this.rect.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.rect.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("rect.BackgroundImage")));
            this.rect.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rect.ButtonText = "Draw Rectangle";
            this.rect.ButtonTextMarginLeft = 0;
            this.rect.ColorContrastOnClick = 45;
            this.rect.ColorContrastOnHover = 45;
            this.rect.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.rect.CustomizableEdges = borderEdges1;
            this.rect.DialogResult = System.Windows.Forms.DialogResult.None;
            this.rect.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.rect.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.rect.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.rect.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.rect.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.rect.ForeColor = System.Drawing.Color.White;
            this.rect.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.rect.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.rect.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.rect.IconMarginLeft = 11;
            this.rect.IconPadding = 10;
            this.rect.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.rect.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.rect.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.rect.IconSize = 25;
            this.rect.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.rect.IdleBorderRadius = 1;
            this.rect.IdleBorderThickness = 1;
            this.rect.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.rect.IdleIconLeftImage = null;
            this.rect.IdleIconRightImage = null;
            this.rect.IndicateFocus = false;
            this.rect.Location = new System.Drawing.Point(38, 29);
            this.rect.Name = "rect";
            this.rect.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.rect.OnDisabledState.BorderRadius = 1;
            this.rect.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rect.OnDisabledState.BorderThickness = 1;
            this.rect.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.rect.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.rect.OnDisabledState.IconLeftImage = null;
            this.rect.OnDisabledState.IconRightImage = null;
            this.rect.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.rect.onHoverState.BorderRadius = 1;
            this.rect.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rect.onHoverState.BorderThickness = 1;
            this.rect.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.rect.onHoverState.ForeColor = System.Drawing.Color.White;
            this.rect.onHoverState.IconLeftImage = null;
            this.rect.onHoverState.IconRightImage = null;
            this.rect.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.rect.OnIdleState.BorderRadius = 1;
            this.rect.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rect.OnIdleState.BorderThickness = 1;
            this.rect.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.rect.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.rect.OnIdleState.IconLeftImage = null;
            this.rect.OnIdleState.IconRightImage = null;
            this.rect.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rect.OnPressedState.BorderRadius = 1;
            this.rect.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.rect.OnPressedState.BorderThickness = 1;
            this.rect.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rect.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.rect.OnPressedState.IconLeftImage = null;
            this.rect.OnPressedState.IconRightImage = null;
            this.rect.Size = new System.Drawing.Size(150, 39);
            this.rect.TabIndex = 0;
            this.rect.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.rect.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.rect.TextMarginLeft = 0;
            this.rect.TextPadding = new System.Windows.Forms.Padding(0);
            this.rect.UseDefaultRadiusAndThickness = true;
            this.rect.Click += new System.EventHandler(this.rect_Click);
            // 
            // circle
            // 
            this.circle.AllowAnimations = true;
            this.circle.AllowMouseEffects = true;
            this.circle.AllowToggling = false;
            this.circle.AnimationSpeed = 200;
            this.circle.AutoGenerateColors = false;
            this.circle.AutoRoundBorders = false;
            this.circle.AutoSizeLeftIcon = true;
            this.circle.AutoSizeRightIcon = true;
            this.circle.BackColor = System.Drawing.Color.Transparent;
            this.circle.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.circle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("circle.BackgroundImage")));
            this.circle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.circle.ButtonText = "Draw circle";
            this.circle.ButtonTextMarginLeft = 0;
            this.circle.ColorContrastOnClick = 45;
            this.circle.ColorContrastOnHover = 45;
            this.circle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.circle.CustomizableEdges = borderEdges2;
            this.circle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.circle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.circle.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.circle.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.circle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.circle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.circle.ForeColor = System.Drawing.Color.White;
            this.circle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.circle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.circle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.circle.IconMarginLeft = 11;
            this.circle.IconPadding = 10;
            this.circle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.circle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.circle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.circle.IconSize = 25;
            this.circle.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.circle.IdleBorderRadius = 1;
            this.circle.IdleBorderThickness = 1;
            this.circle.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.circle.IdleIconLeftImage = null;
            this.circle.IdleIconRightImage = null;
            this.circle.IndicateFocus = false;
            this.circle.Location = new System.Drawing.Point(38, 128);
            this.circle.Name = "circle";
            this.circle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.circle.OnDisabledState.BorderRadius = 1;
            this.circle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.circle.OnDisabledState.BorderThickness = 1;
            this.circle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.circle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.circle.OnDisabledState.IconLeftImage = null;
            this.circle.OnDisabledState.IconRightImage = null;
            this.circle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.circle.onHoverState.BorderRadius = 1;
            this.circle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.circle.onHoverState.BorderThickness = 1;
            this.circle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.circle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.circle.onHoverState.IconLeftImage = null;
            this.circle.onHoverState.IconRightImage = null;
            this.circle.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.circle.OnIdleState.BorderRadius = 1;
            this.circle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.circle.OnIdleState.BorderThickness = 1;
            this.circle.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.circle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.circle.OnIdleState.IconLeftImage = null;
            this.circle.OnIdleState.IconRightImage = null;
            this.circle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.circle.OnPressedState.BorderRadius = 1;
            this.circle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.circle.OnPressedState.BorderThickness = 1;
            this.circle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.circle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.circle.OnPressedState.IconLeftImage = null;
            this.circle.OnPressedState.IconRightImage = null;
            this.circle.Size = new System.Drawing.Size(150, 39);
            this.circle.TabIndex = 1;
            this.circle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.circle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.circle.TextMarginLeft = 0;
            this.circle.TextPadding = new System.Windows.Forms.Padding(0);
            this.circle.UseDefaultRadiusAndThickness = true;
            this.circle.Click += new System.EventHandler(this.circle_Click);
            // 
            // line
            // 
            this.line.AllowAnimations = true;
            this.line.AllowMouseEffects = true;
            this.line.AllowToggling = false;
            this.line.AnimationSpeed = 200;
            this.line.AutoGenerateColors = false;
            this.line.AutoRoundBorders = false;
            this.line.AutoSizeLeftIcon = true;
            this.line.AutoSizeRightIcon = true;
            this.line.BackColor = System.Drawing.Color.Transparent;
            this.line.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.line.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("line.BackgroundImage")));
            this.line.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.line.ButtonText = "Draw line";
            this.line.ButtonTextMarginLeft = 0;
            this.line.ColorContrastOnClick = 45;
            this.line.ColorContrastOnHover = 45;
            this.line.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.line.CustomizableEdges = borderEdges3;
            this.line.DialogResult = System.Windows.Forms.DialogResult.None;
            this.line.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.line.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.line.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.line.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.line.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.line.ForeColor = System.Drawing.Color.White;
            this.line.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.line.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.line.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.line.IconMarginLeft = 11;
            this.line.IconPadding = 10;
            this.line.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.line.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.line.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.line.IconSize = 25;
            this.line.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.line.IdleBorderRadius = 1;
            this.line.IdleBorderThickness = 1;
            this.line.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.line.IdleIconLeftImage = null;
            this.line.IdleIconRightImage = null;
            this.line.IndicateFocus = false;
            this.line.Location = new System.Drawing.Point(38, 215);
            this.line.Name = "line";
            this.line.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.line.OnDisabledState.BorderRadius = 1;
            this.line.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.line.OnDisabledState.BorderThickness = 1;
            this.line.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.line.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.line.OnDisabledState.IconLeftImage = null;
            this.line.OnDisabledState.IconRightImage = null;
            this.line.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.line.onHoverState.BorderRadius = 1;
            this.line.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.line.onHoverState.BorderThickness = 1;
            this.line.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.line.onHoverState.ForeColor = System.Drawing.Color.White;
            this.line.onHoverState.IconLeftImage = null;
            this.line.onHoverState.IconRightImage = null;
            this.line.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.line.OnIdleState.BorderRadius = 1;
            this.line.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.line.OnIdleState.BorderThickness = 1;
            this.line.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.line.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.line.OnIdleState.IconLeftImage = null;
            this.line.OnIdleState.IconRightImage = null;
            this.line.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.line.OnPressedState.BorderRadius = 1;
            this.line.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.line.OnPressedState.BorderThickness = 1;
            this.line.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.line.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.line.OnPressedState.IconLeftImage = null;
            this.line.OnPressedState.IconRightImage = null;
            this.line.Size = new System.Drawing.Size(150, 39);
            this.line.TabIndex = 2;
            this.line.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.line.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.line.TextMarginLeft = 0;
            this.line.TextPadding = new System.Windows.Forms.Padding(0);
            this.line.UseDefaultRadiusAndThickness = true;
            this.line.Click += new System.EventHandler(this.line_Click);
            // 
            // hello
            // 
            this.hello.AllowAnimations = true;
            this.hello.AllowMouseEffects = true;
            this.hello.AllowToggling = false;
            this.hello.AnimationSpeed = 200;
            this.hello.AutoGenerateColors = false;
            this.hello.AutoRoundBorders = false;
            this.hello.AutoSizeLeftIcon = true;
            this.hello.AutoSizeRightIcon = true;
            this.hello.BackColor = System.Drawing.Color.Transparent;
            this.hello.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.hello.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("hello.BackgroundImage")));
            this.hello.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hello.ButtonText = "Write Hello";
            this.hello.ButtonTextMarginLeft = 0;
            this.hello.ColorContrastOnClick = 45;
            this.hello.ColorContrastOnHover = 45;
            this.hello.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.hello.CustomizableEdges = borderEdges4;
            this.hello.DialogResult = System.Windows.Forms.DialogResult.None;
            this.hello.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hello.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hello.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hello.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.hello.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.hello.ForeColor = System.Drawing.Color.White;
            this.hello.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.hello.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.hello.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.hello.IconMarginLeft = 11;
            this.hello.IconPadding = 10;
            this.hello.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.hello.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.hello.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.hello.IconSize = 25;
            this.hello.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.hello.IdleBorderRadius = 1;
            this.hello.IdleBorderThickness = 1;
            this.hello.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.hello.IdleIconLeftImage = null;
            this.hello.IdleIconRightImage = null;
            this.hello.IndicateFocus = false;
            this.hello.Location = new System.Drawing.Point(38, 293);
            this.hello.Name = "hello";
            this.hello.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.hello.OnDisabledState.BorderRadius = 1;
            this.hello.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hello.OnDisabledState.BorderThickness = 1;
            this.hello.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.hello.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.hello.OnDisabledState.IconLeftImage = null;
            this.hello.OnDisabledState.IconRightImage = null;
            this.hello.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hello.onHoverState.BorderRadius = 1;
            this.hello.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hello.onHoverState.BorderThickness = 1;
            this.hello.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.hello.onHoverState.ForeColor = System.Drawing.Color.White;
            this.hello.onHoverState.IconLeftImage = null;
            this.hello.onHoverState.IconRightImage = null;
            this.hello.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.hello.OnIdleState.BorderRadius = 1;
            this.hello.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hello.OnIdleState.BorderThickness = 1;
            this.hello.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.hello.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.hello.OnIdleState.IconLeftImage = null;
            this.hello.OnIdleState.IconRightImage = null;
            this.hello.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hello.OnPressedState.BorderRadius = 1;
            this.hello.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.hello.OnPressedState.BorderThickness = 1;
            this.hello.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.hello.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.hello.OnPressedState.IconLeftImage = null;
            this.hello.OnPressedState.IconRightImage = null;
            this.hello.Size = new System.Drawing.Size(150, 39);
            this.hello.TabIndex = 3;
            this.hello.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.hello.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.hello.TextMarginLeft = 0;
            this.hello.TextPadding = new System.Windows.Forms.Padding(0);
            this.hello.UseDefaultRadiusAndThickness = true;
            this.hello.Click += new System.EventHandler(this.hello_Click);
            // 
            // canvas
            // 
            this.canvas.AllowAnimations = true;
            this.canvas.AllowMouseEffects = true;
            this.canvas.AllowToggling = false;
            this.canvas.AnimationSpeed = 200;
            this.canvas.AutoGenerateColors = false;
            this.canvas.AutoRoundBorders = false;
            this.canvas.AutoSizeLeftIcon = true;
            this.canvas.AutoSizeRightIcon = true;
            this.canvas.BackColor = System.Drawing.Color.Transparent;
            this.canvas.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.canvas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("canvas.BackgroundImage")));
            this.canvas.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.canvas.ButtonText = "Crop Canvas";
            this.canvas.ButtonTextMarginLeft = 0;
            this.canvas.ColorContrastOnClick = 45;
            this.canvas.ColorContrastOnHover = 45;
            this.canvas.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.canvas.CustomizableEdges = borderEdges5;
            this.canvas.DialogResult = System.Windows.Forms.DialogResult.None;
            this.canvas.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.canvas.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.canvas.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.canvas.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.canvas.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.canvas.ForeColor = System.Drawing.Color.White;
            this.canvas.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.canvas.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.canvas.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.canvas.IconMarginLeft = 11;
            this.canvas.IconPadding = 10;
            this.canvas.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.canvas.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.canvas.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.canvas.IconSize = 25;
            this.canvas.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.canvas.IdleBorderRadius = 1;
            this.canvas.IdleBorderThickness = 1;
            this.canvas.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.canvas.IdleIconLeftImage = null;
            this.canvas.IdleIconRightImage = null;
            this.canvas.IndicateFocus = false;
            this.canvas.Location = new System.Drawing.Point(38, 369);
            this.canvas.Name = "canvas";
            this.canvas.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.canvas.OnDisabledState.BorderRadius = 1;
            this.canvas.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.canvas.OnDisabledState.BorderThickness = 1;
            this.canvas.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.canvas.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.canvas.OnDisabledState.IconLeftImage = null;
            this.canvas.OnDisabledState.IconRightImage = null;
            this.canvas.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.canvas.onHoverState.BorderRadius = 1;
            this.canvas.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.canvas.onHoverState.BorderThickness = 1;
            this.canvas.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.canvas.onHoverState.ForeColor = System.Drawing.Color.White;
            this.canvas.onHoverState.IconLeftImage = null;
            this.canvas.onHoverState.IconRightImage = null;
            this.canvas.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.canvas.OnIdleState.BorderRadius = 1;
            this.canvas.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.canvas.OnIdleState.BorderThickness = 1;
            this.canvas.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.canvas.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.canvas.OnIdleState.IconLeftImage = null;
            this.canvas.OnIdleState.IconRightImage = null;
            this.canvas.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.canvas.OnPressedState.BorderRadius = 1;
            this.canvas.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.canvas.OnPressedState.BorderThickness = 1;
            this.canvas.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.canvas.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.canvas.OnPressedState.IconLeftImage = null;
            this.canvas.OnPressedState.IconRightImage = null;
            this.canvas.Size = new System.Drawing.Size(150, 39);
            this.canvas.TabIndex = 4;
            this.canvas.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.canvas.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.canvas.TextMarginLeft = 0;
            this.canvas.TextPadding = new System.Windows.Forms.Padding(0);
            this.canvas.UseDefaultRadiusAndThickness = true;
            this.canvas.Click += new System.EventHandler(this.canvas_Click);
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.bunifuDataGridView1.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.operation});
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(300, 12);
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.RowHeadersVisible = false;
            this.bunifuDataGridView1.RowHeadersWidth = 51;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(240, 410);
            this.bunifuDataGridView1.TabIndex = 5;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // operation
            // 
            this.operation.HeaderText = "Operations";
            this.operation.MinimumWidth = 6;
            this.operation.Name = "operation";
            // 
            // undo
            // 
            this.undo.AllowAnimations = true;
            this.undo.AllowMouseEffects = true;
            this.undo.AllowToggling = false;
            this.undo.AnimationSpeed = 200;
            this.undo.AutoGenerateColors = false;
            this.undo.AutoRoundBorders = false;
            this.undo.AutoSizeLeftIcon = true;
            this.undo.AutoSizeRightIcon = true;
            this.undo.BackColor = System.Drawing.Color.Transparent;
            this.undo.BackColor1 = System.Drawing.Color.Red;
            this.undo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("undo.BackgroundImage")));
            this.undo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.undo.ButtonText = "Undo";
            this.undo.ButtonTextMarginLeft = 0;
            this.undo.ColorContrastOnClick = 45;
            this.undo.ColorContrastOnHover = 45;
            this.undo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.undo.CustomizableEdges = borderEdges6;
            this.undo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.undo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.undo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.undo.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.undo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.undo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.undo.ForeColor = System.Drawing.Color.White;
            this.undo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.undo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.undo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.undo.IconMarginLeft = 11;
            this.undo.IconPadding = 10;
            this.undo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.undo.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.undo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.undo.IconSize = 25;
            this.undo.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.undo.IdleBorderRadius = 1;
            this.undo.IdleBorderThickness = 1;
            this.undo.IdleFillColor = System.Drawing.Color.Red;
            this.undo.IdleIconLeftImage = null;
            this.undo.IdleIconRightImage = null;
            this.undo.IndicateFocus = false;
            this.undo.Location = new System.Drawing.Point(608, 215);
            this.undo.Name = "undo";
            this.undo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.undo.OnDisabledState.BorderRadius = 1;
            this.undo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.undo.OnDisabledState.BorderThickness = 1;
            this.undo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.undo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.undo.OnDisabledState.IconLeftImage = null;
            this.undo.OnDisabledState.IconRightImage = null;
            this.undo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.undo.onHoverState.BorderRadius = 1;
            this.undo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.undo.onHoverState.BorderThickness = 1;
            this.undo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.undo.onHoverState.ForeColor = System.Drawing.Color.White;
            this.undo.onHoverState.IconLeftImage = null;
            this.undo.onHoverState.IconRightImage = null;
            this.undo.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.undo.OnIdleState.BorderRadius = 1;
            this.undo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.undo.OnIdleState.BorderThickness = 1;
            this.undo.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.undo.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.undo.OnIdleState.IconLeftImage = null;
            this.undo.OnIdleState.IconRightImage = null;
            this.undo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.undo.OnPressedState.BorderRadius = 1;
            this.undo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.undo.OnPressedState.BorderThickness = 1;
            this.undo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.undo.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.undo.OnPressedState.IconLeftImage = null;
            this.undo.OnPressedState.IconRightImage = null;
            this.undo.Size = new System.Drawing.Size(150, 39);
            this.undo.TabIndex = 6;
            this.undo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.undo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.undo.TextMarginLeft = 0;
            this.undo.TextPadding = new System.Windows.Forms.Padding(0);
            this.undo.UseDefaultRadiusAndThickness = true;
            this.undo.Click += new System.EventHandler(this.undo_Click);
            // 
            // count
            // 
            this.count.AcceptsReturn = false;
            this.count.AcceptsTab = false;
            this.count.AnimationSpeed = 200;
            this.count.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.count.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.count.BackColor = System.Drawing.Color.Transparent;
            this.count.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("count.BackgroundImage")));
            this.count.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.count.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.count.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.count.BorderColorIdle = System.Drawing.Color.Silver;
            this.count.BorderRadius = 1;
            this.count.BorderThickness = 1;
            this.count.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.count.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.count.DefaultFont = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.count.DefaultText = "0";
            this.count.FillColor = System.Drawing.Color.White;
            this.count.HideSelection = true;
            this.count.IconLeft = null;
            this.count.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.count.IconPadding = 10;
            this.count.IconRight = null;
            this.count.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.count.Lines = new string[] {
        "0"};
            this.count.Location = new System.Drawing.Point(617, 29);
            this.count.MaxLength = 32767;
            this.count.MinimumSize = new System.Drawing.Size(1, 1);
            this.count.Modified = false;
            this.count.Multiline = false;
            this.count.Name = "count";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.count.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.count.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.count.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.count.OnIdleState = stateProperties4;
            this.count.Padding = new System.Windows.Forms.Padding(3);
            this.count.PasswordChar = '\0';
            this.count.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.count.PlaceholderText = "";
            this.count.ReadOnly = false;
            this.count.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.count.SelectedText = "";
            this.count.SelectionLength = 0;
            this.count.SelectionStart = 1;
            this.count.ShortcutsEnabled = true;
            this.count.Size = new System.Drawing.Size(123, 60);
            this.count.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.count.TabIndex = 7;
            this.count.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.count.TextMarginBottom = 0;
            this.count.TextMarginLeft = 3;
            this.count.TextMarginTop = 0;
            this.count.TextPlaceholder = "";
            this.count.UseSystemPasswordChar = false;
            this.count.WordWrap = true;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.count);
            this.Controls.Add(this.undo);
            this.Controls.Add(this.bunifuDataGridView1);
            this.Controls.Add(this.canvas);
            this.Controls.Add(this.hello);
            this.Controls.Add(this.line);
            this.Controls.Add(this.circle);
            this.Controls.Add(this.rect);
            this.Name = "Form1";
            this.Text = "Form1";
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton rect;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton circle;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton line;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton hello;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton canvas;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private System.Windows.Forms.DataGridViewTextBoxColumn operation;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton undo;
        private Bunifu.UI.WinForms.BunifuTextBox count;
    }
}

